import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/montserrat";
import "@fontsource/inter";
import "@fontsource/red-hat-display";
import "@fontsource/poppins";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
